# Generated by Django 4.2.4 on 2023-08-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adc',
            new_name='Ads',
        ),
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'Ads', 'verbose_name_plural': 'Ads'},
        ),
    ]
