# Generated by Django 4.2.4 on 2023-08-17 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_adc_ads_alter_ads_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ads',
            name='type',
            field=models.CharField(choices=[('Хочьу научиться', 'Хочьу научиться'), ('Могу научиться', 'Могу научиться')], default='Хочьу научиться', max_length=100),
        ),
        migrations.AddField(
            model_name='ads',
            name='updated_ad',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
